### PR TITLE
Set the noTabsBackground to the same as editor background

### PR DESCRIPTION
**Pull request by amalchuk**
Before:
Screenshot 2024-03-03 at 01 23 26

After:
Screenshot 2024-03-03 at 01 25 41

### CODE REVIEW

**Comment by amalchuk** [comment]
@jdinhify Do you approve?

**Comment by amalchuk** [comment]
Closed due maintainer's inactivity.

**Comment by jdinhify** [comment]
@amalchuk apologies

could you reopen this & I'll get this merged/deployed?

**Comment by amalchuk** [comment]
> @amalchuk apologies
> 
> could you reopen this & I'll get this merged/deployed?

Hello, @jdinhify 🙂
Reopened into #100.

**Pull request closed without merging**
