### PR TITLE
Add menu border

### PR DESCRIPTION
**Pull request by tty7tyil**
Currently there are no border for menus, which blends with the editor background.

### CODE REVIEW

**Comment by jdinhify** [comment]
Thanks @tty7tyil 

I'll merge this and ship soon

**Review by jdinhify — APPROVED** [review]

**Comment by jdinhify** [comment]
@tty7tyil actually, could you please add yourself to the end of the contributor list in `package.json` & `README.md`

**Comment by tty7tyil** [comment]
This is just a minor change, I don’t mind not being in the list.

**Comment by jdinhify** [comment]
Anything, no matter small or big, is a contribution 🙏 . I just want to acknowledge everyone's involvement.
Unless you don't want to be in the list @tty7tyil (it's fine if this is the case, please just let me know)

**Comment by jdinhify** [comment]
I'll merge this after another day, thanks @tty7tyil

**Pull request merged**
